# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'egel/tmux-gruvbox'

set-window-option -g mode-keys vi
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
set -g @tmux-gruvbox 'dark'
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=white,bg=black'
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g @resurrect-capture-pane-contents 'off'
set-option -g allow-rename off
set-window-option -g automatic-rename off
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Initialize TMUX plugin manager (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
